theme: jekyll-theme-architect

title: [openmq]
description: [Open Message Queue (Open MQ) -- A complete JMS MOM Platform]

# sidebar links url
links:
  source: https://github.com/javaee/openmq
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

